### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by luckypoem** [sewh/tinydnsproxy-v1#1]
hi.

git clone https://github.com/sewh/tinydnsproxy tinydnsproxy-by-sewh
cd tinydnsproxy-by-sewh
sudo cargo build --release
it shows:
...
Compiling toml v0.5.5
    Building [======================================================>  ] 66/68 
   Compiling tinydnsproxy v0.1.0 (/Users/yuming/tinydnsproxy-by-sewh)
error[E0008]: cannot bind by-move into a pattern guard
   --> src/listener.rs:130:21
    |
130 |                 Err(e) if e.kind() == io::ErrorKind::WouldBlock => {
    |                     ^ moves value into pattern guard
    |
    = help: add `#![feature(bind_by_move_pattern_guards)]` to the crate attributes to enable

error[E0008]: cannot bind by-move into a pattern guard
   --> src/listener.rs:133:21
    |
133 |                 Err(e) if e.kind() == io::ErrorKind::TimedOut => {
    |                     ^ moves value into pattern guard
    |
    = help: add `#![feature(bind_by_move_pattern_guards)]` to the crate attributes to enable

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0008`.
error: Could not compile `tinydnsproxy`.

To learn more, run the command again with --verbose.
yudeMacBook-Air:tinydnsproxy-by-sewh brite$

how to fix the errors?

**Comment by sewh** [comment]
Hi. I replicated your procedure and it built fine for me (on macOS - stable-x86_64-apple-darwin). Are you using the latest version of Rust? You can update to the latest version by running `rustup update` if you installed rust via rustup. 

Another thing you can try is (if you have a host that's running Docker) doing `make x64-release`. This creates a Linux build environment and builds a x86_64 Linux version of the program - I just tried that again and that works too.

My version of Cargo and rustc:

```
cargo --version
cargo 1.40.0 (bc8e4c8be 2019-11-22)

rustc --version
rustc 1.40.0 (73528e339 2019-12-16)
```

**Comment by luckypoem** [comment]
yes,after updating the cargo and rustc,it's ok

**Comment by sewh** [comment]
Glad to hear it 🙂
